export const defaultState = {
  advanced: false,
  keyword: "",
  searchIn: {
    name: true,
    description: false,
    readme: false,
  },
  page: 1,
  perPage: 10,
  sortBy: 'default',
  orderBy: 'asc',
  language: [],
  topic: [],
  username: '',
  organization: '',
  starsIs: '>=',
  starsValue: null,
  starsMin: null,
  starsMax: null,
  sizeIs: '>=',
  sizeValue: null,
  sizeMin: null,
  sizeMax: null,
  createdIs: '<=',
  createdValue: null,
  createdMin: null,
  createdMax: null
}